name: Verify and Runtime Smoke

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps (memory server)
        run: |
          python -m pip install --upgrade pip
          pip install -r servers/requirements.txt

      - name: Install Node deps
        run: npm ci

      - name: Type check and lint
        run: npm run verify

      - name: Runtime smoke
        env:
          ONEAGENT_MEMORY_PORT: '8010'
          ONEAGENT_MCP_PORT: '8083'
        run: npm run smoke:runtime

      - name: A2A canonical tests
        env:
          ONEAGENT_FAST_TEST_MODE: '1'
          ONEAGENT_DISABLE_AUTO_MONITORING: '1'
        run: npm run test:a2a

  persistence-nlacs:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps (memory server)
        run: |
          python -m pip install --upgrade pip
          pip install -r servers/requirements.txt

      - name: Install Node deps
        run: npm ci

      - name: Type check and lint
        run: npm run verify

      - name: NLACS persistence test (with memory readiness)
        env:
          ONEAGENT_MEMORY_PORT: '8010'
          MEM0_API_KEY: 'ci-test-key'
          GEMINI_API_KEY: 'ci-dummy-key'
        run: |
          # Start memory server in background via uvicorn
          python -m uvicorn oneagent_memory_server:app --app-dir servers --host 127.0.0.1 --port $ONEAGENT_MEMORY_PORT &
          MEM_PID=$!
          # Wait for readiness
          for i in {1..120}; do
            if curl -fsS http://127.0.0.1:$ONEAGENT_MEMORY_PORT/readyz >/dev/null 2>&1; then
              echo "Memory ready"
              break
            fi
            sleep 0.5
          done
          # Run NLACS persistence test (non-fast-mode)
          node -r ts-node/register tests/canonical/a2a-nlacs-canonical.test.ts
          # Cleanup
          kill $MEM_PID

  persistence-nlacs-windows:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps (memory server)
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install -r servers/requirements.txt

      - name: Install Node deps
        shell: pwsh
        run: npm ci

      - name: Type check and lint
        shell: pwsh
        run: npm run verify

      - name: NLACS persistence test (with memory readiness, Windows)
        shell: pwsh
        env:
          ONEAGENT_MEMORY_PORT: '8010'
          MEM0_API_KEY: 'ci-test-key'
          GEMINI_API_KEY: 'ci-dummy-key'
        run: |
          # Start memory server in background via uvicorn
          $proc = Start-Process -FilePath python -ArgumentList @('-m','uvicorn','oneagent_memory_server:app','--app-dir','servers','--host','127.0.0.1','--port',$env:ONEAGENT_MEMORY_PORT) -PassThru
          try {
            # Wait for readiness
            $max = 120
            for ($i=0; $i -lt $max; $i++) {
              try {
                $resp = Invoke-WebRequest -UseBasicParsing -Uri ("http://127.0.0.1:{0}/readyz" -f $env:ONEAGENT_MEMORY_PORT) -TimeoutSec 2
                if ($resp.StatusCode -eq 200) { Write-Host "Memory ready"; break }
              } catch { }
              Start-Sleep -Milliseconds 500
            }
            # Run NLACS persistence test (non-fast-mode)
            node -r ts-node/register tests/canonical/a2a-nlacs-canonical.test.ts
          } finally {
            # Cleanup
            try { Stop-Process -Id $proc.Id -Force } catch {}
          }

  build-and-smoke-windows:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps (memory server)
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install -r servers/requirements.txt

      - name: Install Node deps
        shell: pwsh
        run: npm ci

      - name: Type check and lint
        shell: pwsh
        run: npm run verify

      - name: Runtime smoke (Windows)
        shell: pwsh
        env:
          ONEAGENT_MEMORY_PORT: '8010'
          ONEAGENT_MCP_PORT: '8083'
        run: npm run smoke:runtime

      - name: A2A canonical tests (Windows)
        shell: pwsh
        env:
          ONEAGENT_FAST_TEST_MODE: '1'
          ONEAGENT_DISABLE_AUTO_MONITORING: '1'
        run: npm run test:a2a
